server:
  port: 8081

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: provider-order
          uri: lb://provider-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: customer-order
          uri: lb://customer-order
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    org.springframework.cloud.gateway: debug



